### ISSUE TITLE
k8s-policy-no-match order

### ISSUE THREAD

**Issue by emptywee** [projectcalico/k8s-policy#68]
Not really an issue, more like a question. Why was it assigned order number 2000?

https://github.com/projectcalico/k8s-policy/blob/master/constants.py#L41

Can it be altered somehow? I 'd like to have a broader range of rules, so I can devote at least 1000 per namespace.

Thank you.

**Comment by caseydavenport** [comment]
@emptywee it was assigned an order of 2000 in order to provide what was considered enough room  for users to insert policy before it.

If we it turns out you need more than 1000 subdivisions between your NetworkPolicy and the default policy, then we can consider changing!

My question would be: Do you really need more than 1000 subdivisions?  Note that you can have multiple policies with the same order.

**Comment by emptywee** [comment]
@caseydavenport It's more like a convenience, than the limit. People are used to leave gaps in the numbering of rules so they can insert another set of rules where needed. And typically you are limited to about 65k rules. I am not saying that I am going to add 2000 rules. But let's say I am gonna have 25 namespaces and I would like to allocate a range of 100 rules for each.

namespace1 - 100 to 199,
namespace2 - 200 to 299,
...
namepsace20 - 2000 to 2099 is not gonna fit. 

Again, it's more about convenience. What harm would it do if you raise that number to 65000? If it is going to affect performance or have some other negative effect, then I'll understand and get over it :) If it's not, then I see no point in limiting everybody to 2000.

That is why I am asking. More like a discussion.

**Comment by caseydavenport** [comment]
Shouldn't cause any harm to raise it :)

I think we can even set it to None, which means "this one is always last" (but I have to double check that!).

At the very least, we could make it configurable!

**Comment by emptywee** [comment]
That's be awesome, man :-)
