### ISSUE TITLE
Project has more than one image name on quay

### ISSUE THREAD

**Issue by tomdee** [projectcalico/k8s-policy#71]
https://quay.io/repository/calico/kube-policy-controller
https://quay.io/repository/calico/k8s-policy-agent (edited)

k8s-policy-agent is what it was called when NetworkPolicy was in alpha.  We switched names when it moved to beta to be consistent with k8s naming practices.

Some of our automation still appears to be pushing to the old one though.  Not sure how / why.

**Comment by caseydavenport** [comment]
The k8s-policy-agent repository had a build trigger configured.

I've disabled the build trigger and removed tags from that repository that for v0.2.0+, so that the original distinction between the two remains.

So:
- calico/kube-policy-controller is the active version, supporting the v1beta1 (and eventually v1) API.
- calico/k8s-policy-agent is legacy, supporting the v1alpha1 version of the API.
